### ISSUE TITLE
Why can't we set password_digest even if model is not valid?

### ISSUE THREAD

**Issue by asiniy** [tuvistavie/ecto-secure-password#4]
Hey!

I meet strange code logic and can't understand these two lines: https://github.com/tuvistavie/ecto-secure-password/blob/master/lib/secure_password.ex#L84-L85 . It looks like I can't understand something in saving logic, but: why can't this package `set_password_digest` even if this model is invalid?

**Comment by tuvistavie** [comment]
Hi!

If I remember correctly, I added this because hashing takes some CPU resource,
so I thought it would be better to skip it if we already know the resource will not be saved anyway.
Is that causing you a problem? If this is the case, I do not mind changing the logic here.

**Comment by asiniy** [comment]
Gotcha
