### ISSUE TITLE
The purpose of `delete_change`?

### ISSUE THREAD

**Issue by asiniy** [tuvistavie/ecto-secure-password#7]
Hey @tuvistavie I have a question. What's the purpose of deleting changes of `password` and `password_confirmation` there: https://github.com/tuvistavie/ecto-secure-password/blob/master/lib/secure_password.ex#L118

The library behaves a little bit strange. IE I have

``` elixir
changeset
|> with_secure_password
|> validate_password_complexity
```

and I can't access to `password` in `validate_password_complexity`.

**Comment by asiniy** [comment]
@tuvistavie I doubt in your solution. What is the purpose of `with_secure_password`? Actually - to generate password digest for valid password. Let's put responsibility on paranoic hands directly and loudly.

So, in my opinion this functionality have to be removed at all.

**Comment by tuvistavie** [comment]
@asiniy You are right, let's get rid of this functionality. Would you mind sending a PR?

**Comment by asiniy** [comment]
@tuvistavie np
